name: 'Doxygen Action'
description: 'Generate documentation on a commented project using doxygen'
icon: 'book-open'
color: 'gray-dark'
inputs:
  doxyfile-path:
    description: 'Path to Doxyfile'
    required: true
    default: './Doxyfile'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doxyfile-path }}
